# Source: jx-build-controller/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-x-controllerbuild
  labels:
    app: jx-build-controller
    chart: jx-build-controller-0.3.20
    release: jx-build-controller
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    iam.gke.io/gcp-service-account: tf-jx-outgoing-bunny-bc@devops-2k22.iam.gserviceaccount.com
    meta.helm.sh/release-name: 'jx-build-controller'
  namespace: jx
